"""
    Marktdatenstammregister API

    Das MaStR führt die Stammdaten zu Strom- und Gaserzeugungsanlagen sowie Marktakteuren wie Anlagenbetreibern, Netzbetreibern und Energielieferanten.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.marktstammdaten.api.filter_api import FilterApi  # noqa: E501

from deutschland import marktstammdaten


class TestFilterApi(unittest.TestCase):
    """FilterApi unit test stubs"""

    def setUp(self):
        self.api = FilterApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_gaserzeugung_get(
        self,
    ):
        """Test case for einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_gaserzeugung_get

        Filter für erweiterte Gaserzeugung abfragen  # noqa: E501
        """
        pass

    def test_einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_gasverbrauch_get(
        self,
    ):
        """Test case for einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_gasverbrauch_get

        Filter für erweiterten Gasverbrauch abfragen  # noqa: E501
        """
        pass

    def test_einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_stromerzeugung_get(
        self,
    ):
        """Test case for einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_stromerzeugung_get

        Filter für erweiterte Stromerzeugung abfragen  # noqa: E501
        """
        pass

    def test_einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_stromverbrauch_get(
        self,
    ):
        """Test case for einheit_einheit_json_get_filter_columns_erweiterte_oeffentliche_einheit_stromverbrauch_get

        Filter für erweiterten Stromverbrauch abfragen  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
