"""
    Marktdatenstammregister API

    Das MaStR führt die Stammdaten zu Strom- und Gaserzeugungsanlagen sowie Marktakteuren wie Anlagenbetreibern, Netzbetreibern und Energielieferanten.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.marktstammdaten.model.entry import Entry

from deutschland import marktstammdaten

globals()["Entry"] = Entry
from deutschland.marktstammdaten.model.einheit_einheit_json_get_erweiterte_oeffentliche_einheit_stromerzeugung_get200_response import (
    EinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response,
)


class TestEinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response(
    unittest.TestCase
):
    """EinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response(
        self,
    ):
        """Test EinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EinheitEinheitJsonGetErweiterteOeffentlicheEinheitStromerzeugungGet200Response()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
